### ISSUE TITLE
Does this library support filtering on nested associations tables (joined tables fields)?

### ISSUE THREAD

**Issue by acrolink** [valyukov/ex_sive#10]

**Comment by valyukov** [comment]
Sure, look at readme examples.

**Comment by acrolink** [comment]
I have tried something like this as outlined in the readme examples:
```
"comments_body_eq": "body",
```
But it is not working at all. I am using Phoenix 1.3 and suspect that this might be due to the newly introduced contexts.

**Comment by valyukov** [comment]
Could you please provide a full example or simple test that could help to reproduce issue? Because this example works fine for me.

**Comment by acrolink** [comment]
I have properties belonging to users. A property has a user_id field referencing it to a user. I tried to do users_name_cont but nothing happens.

**Comment by valyukov** [comment]
Did you expect that ex_sieve detect relation and make join instead of you? It doesn't work that way, you should make explicit join before apply ex_sieve filters.

**Comment by ekarak** [comment]
Actually, this functionality only works one level deep, and it would be immensely useful to filter on arbitrary nested fields. Right now, one can only do filters like `parent_child_field_predicate` and cannot do stuff like `(grand+)parent_parent_child_field_predicate`. 
To give an example, in the typical Phoenix demo schema, there are Users that have_many Posts that have_many Comments. I'd like to be able to pass in a filter like
`user_post_comment_text_cont=Elias` to find all users whose posts have a comment that mention my name. I found that recursing into nested structs is stopping at the 1st descendant in `ExSieve.Node.Attribute.get_name/2` [here](https://github.com/valyukov/ex_sieve/blob/master/lib/ex_sieve/node/attribute.ex#L37) and recursion is possible by replacing `get_name` by `extract`:
```
  #defp get_name(%{related: module}, key), do: get_name(module, key)
  defp get_name(%{related: module}, key), do: extract(key, module)
```

... however things get messy after this as the `dynamic_predicate` function in Builder.Where needs to unroll the recursed Attributes returned. I've tried things like:
```
  # ekarak: recurse on higher-order nestings
  defp dynamic_predicate(pred, %Attribute{parent: parent, name: %Attribute{} = child}, value) do
    IO.inspect("pred=#{pred} parent=#{inspect(parent)} child=#{inspect(child)}", label: "dynamic_predicate -->")
    values = dynamic_predicate(pred, %Attribute{parent: child.parent, name: child.name}, value)
    |> IO.inspect(label: "values")
#    dynamic_predicate(pred, parent, values)
    dynamic([{^parent, p}], field(p, :id) in ^values)
    |> IO.inspect(label: "<-- dynamic_predicate #{inspect(parent)}")
  end
``` 
Any help appreciated, especially by @albertored who did changes here recently. 

Thanks!

**Comment by albertored** [comment]
Hi @ekarak, as soon as I find some free time I will take a look at it

**Comment by albertored** [comment]
@ekarak I think I have something working, in the next days I will clean up the code a little bit a push it

**Comment by ekarak** [comment]
Thats great, thanks @albertored !

**Comment by albertored** [comment]
@ekarak I have just pushed a branch with the new feature, if you want you can give it a try

**Comment by ekarak** [comment]
thank you @albertored ! Will test asap

**Comment by ekarak** [comment]
This works beautifully! I want to test it a bit more (mainly to check for edge cases). @valyukov can you take a look as well?
