### ISSUE TITLE
Does not work with ecto 2.1.3

### ISSUE THREAD

**Issue by s33m4nn** [valyukov/ex_sive#5]
The main changes:

In ecto 2.0
@spec escape_binding(list) :: Keyword.t
def escape_binding(binding) when is_list(binding) do

changed to

In ecto 2.1.3
@spec escape_binding(Macro.t | Ecto.Query.t, list) :: {Macro.t | Ecto.Query.t, Keyword.t}
  def escape_binding(query, binding) when is_list(binding) do

-----

In ecto 2.0
@spec build(:where | :having, Macro.t, [Macro.t], Macro.t, Macro.Env.t) :: Macro.t
def build(kind, query, _binding, {:^, _, [var]}, env) do

changed to

in ecto 2.1.3
@spec build(:where | :having, :and | :or, Macro.t, [Macro.t], Macro.t, Macro.Env.t) :: Macro.t
def build(kind, op, query, _binding, {:^, _, [var]}, env) do

[ex_sieve_ecto_2_1_patch.diff.zip](https://github.com/valyukov/ex_sieve/files/813517/ex_sieve_ecto_2_1_patch.diff.zip)

**Comment by valyukov** [comment]
That's grate, thank you for you efforts.
But could you make pull request instead of path?
